# Copyright (C) 2026, Advanced Micro Devices, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Register slices on the streams between islands.

Every stream that crosses from one island to another gets a 2-entry skid buffer at both ends:
data, valid and ready are registered on both sides, so the net between two islands is a single
flip-flop-to-flip-flop connection with one load (instead of a stream bit fanning out to every
SIMD lane of the consumer, through LUTs, timed only when the whole design is assembled). The
assembly's router then finds the crossings timing-clean and has nothing to rip up; the stitcher
routes one pin per crossing bit. Each slice adds one cycle of latency and buffering, never a
throughput loss (full rate), and cannot deadlock a dataflow pipeline (it only adds capacity).

The slices are synthesized out of context once per stream width (component rwiregslice<W>) next
to the nodes, and instantiated in the island netlists like the nodes (black boxes filled from
their checkpoints at link time).
"""

import os

PORTS = ("clk", "rst", "s_data", "s_valid", "s_ready", "m_data", "m_valid", "m_ready")


def regslice_name(width):
    return "rwiregslice%d" % width


def regslice_verilog(width):
    """Skid buffer: s_ready and m_valid/m_data come straight from registers. rst is FINN's
    active-low ap_rst_n."""
    n, w = regslice_name(width), width
    bus = "[%d:0] " % (w - 1) if w > 1 else ""
    return """// generated by finn.util.rwislands.regslice
module %(n)s (
    input clk,
    input rst,
    input %(bus)ss_data,
    input s_valid,
    output s_ready,
    output %(bus)sm_data,
    output m_valid,
    input m_ready
);
    reg %(bus)sd0, d1;
    reg v0 = 1'b0, v1 = 1'b0;
    // (not ready in reset: islands may leave reset a few cycles apart, see assembly.py)
    assign s_ready = ~v1 & rst;
    assign m_valid = v0;
    assign m_data = d0;
    always @(posedge clk) begin
        if (!rst) begin
            v0 <= 1'b0;
            v1 <= 1'b0;
        end else if (!v0 || m_ready) begin
            // output slot free or drained: refill from the skid slot, else from the input
            if (v1) begin
                d0 <= d1;
                v0 <= 1'b1;
                v1 <= 1'b0;
            end else begin
                d0 <= s_data;
                v0 <= s_valid;
            end
        end else if (s_valid && !v1) begin
            // output stalled: park the accepted word in the skid slot
            d1 <= s_data;
            v1 <= 1'b1;
        end
    end
endmodule
""" % {"n": n, "bus": bus}


def regslice_stub(width):
    bus = "[%d:0] " % (width - 1) if width > 1 else ""
    return (
        "(* black_box *)\nmodule %s (\n    input clk,\n    input rst,\n    input %ss_data,\n    input s_valid,\n"
        "    output s_ready,\n    output %sm_data,\n    output m_valid,\n    input m_ready\n);\nendmodule\n"
        % (regslice_name(width), bus, bus)
    )


def regslice_synth_tcl(widths, work, synth_dir, part, synth_args):
    """One Vivado session synthesizing the slices of all widths (checkpoint + utilization like
    the node components)."""
    d = os.path.join(work, "components", "regslices")
    os.makedirs(d, exist_ok=True)
    t = ["set_param general.maxThreads 1"]
    for w in sorted(set(widths)):
        n = regslice_name(w)
        v = os.path.join(d, n + ".v")
        with open(v, "w") as f:
            f.write(regslice_verilog(w))
        t += [
            "read_verilog %s" % v,
            "synth_design -top %s -part %s -mode out_of_context %s" % (n, part, synth_args),
            "write_checkpoint -force %s" % os.path.join(synth_dir, n + "_synth.dcp"),
            "report_utilization -file %s" % os.path.join(synth_dir, n + ".util"),
            "close_design",
            "remove_files -quiet [get_files -quiet]",
        ]
    return d, "\n".join(t) + "\n"


def regslice_res(width):
    """Resources of one slice for the floorplan (2 x width flip-flops, a mux LUT per bit)."""
    return {"lut": width + 4, "ff": 2 * width + 2}
