# Copyright (C) 2026, Advanced Micro Devices, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Turning FINN dataflow nodes into pre-implemented DynaRapid components.

Every node becomes one component:
  1. a single-node Vivado block design, built with the node's own IPI commands
     (the same ones CreateStitchedIP uses), so HLS IP, RTL modules and weight
     streamers are wired exactly as in the regular FINN flow;
  2. a thin Verilog adapter renaming the AXI-Stream ports to DynaRapid's
     elastic-channel convention (dataInArray_i/pValidArray_i/readyArray_i,
     dataOutArray_j/validArray_j/nReadyArray_j, clk, rst);
  3. out-of-context synthesis into DynaRapid's work directory;
  4. DynaRapid pblock generation (placement and routing inside a pblock with
     the ports routed to its boundary) and the placement database.

Components are named after a hash of everything that determines their netlist,
so identical nodes (within a model or across builds) share one library entry.
"""

import hashlib
import json
import os
from qonnx.custom_op.registry import getCustomOp

from finn.transformation.fpgadataflow.create_stitched_ip import CreateStitchedIP
from finn.util.dynarapid.tools import (
    PART_TO_DYNARAPID,
    dynarapid_env,
    dynarapid_root,
    run_java,
    run_vivado,
)

# node attributes that do not influence the generated hardware
_VOLATILE_ATTRS = {
    "code_gen_dir_cppsim",
    "code_gen_dir_ipgen",
    "ipgen_path",
    "ip_path",
    "ip_vlnv",
    "executable_path",
    "rtlsim_so",
    "rtlsim_trace",
    "exec_mode",
    "res_estimate",
    "res_hls",
    "res_synth",
    "cycles_estimate",
    "cycles_rtlsim",
    "partition_id",
    "slr",
    "mem_port",
    "device_id",
}


def component_name(model, node, part, clk_ns):
    """Content-addressed component name: <optype><hash>, no underscores.

    DynaRapid parses pblock names (<dcp>_I<i>_J<j>_R<r>_C<c>) by searching for
    the first "_I", "_J", ... so the component name itself must not contain '_'.
    """
    h = hashlib.sha256()
    h.update(("%s|%s|%s" % (node.op_type, part, clk_ns)).encode())
    for a in sorted(node.attribute, key=lambda a: a.name):
        if a.name in _VOLATILE_ATTRS:
            continue
        h.update(a.SerializeToString())
    for t in node.input:
        init = model.get_initializer(t)
        if init is not None:
            h.update(init.tobytes())
            h.update(str(model.get_tensor_datatype(t)).encode())
        else:
            h.update(str(model.get_tensor_datatype(t)).encode())
    for t in node.output:
        h.update(str(model.get_tensor_datatype(t)).encode())
    short = node.op_type.replace("_", "").lower()
    # "_I"/"_J"/"_R"/"_C" are matched case-sensitively, lowercase is safe
    return "%sx%s" % (short, h.hexdigest()[:12])


def stream_interfaces(node):
    """(inputs, outputs) as lists of (verilog interface name, padded width)."""
    intf = getCustomOp(node).get_verilog_top_module_intf_names()
    unsupported = [k for k in ("axilite", "aximm", "ap_none", "clk2x") if intf.get(k)]
    assert not unsupported, "%s: interfaces %s not supported by the DynaRapid flow" % (
        node.name,
        unsupported,
    )
    return [(n, int(w)) for n, w in intf["s_axis"]], [(n, int(w)) for n, w in intf["m_axis"]]


def adapter_verilog(dcp, bd_name, n_in, n_out, in_widths, out_widths):
    ports = ["    input clk", "    input rst"]
    conns = ["        .ap_clk(clk)", "        .ap_rst_n(rst)"]
    for i in range(n_in):
        ports += [
            "    input [%d:0] dataInArray_%d" % (in_widths[i] - 1, i),
            "    input pValidArray_%d" % i,
            "    output readyArray_%d" % i,
        ]
        conns += [
            "        .s_axis_%d_tdata(dataInArray_%d)" % (i, i),
            "        .s_axis_%d_tvalid(pValidArray_%d)" % (i, i),
            "        .s_axis_%d_tready(readyArray_%d)" % (i, i),
        ]
    for j in range(n_out):
        ports += [
            "    output [%d:0] dataOutArray_%d" % (out_widths[j] - 1, j),
            "    output validArray_%d" % j,
            "    input nReadyArray_%d" % j,
        ]
        conns += [
            "        .m_axis_%d_tdata(dataOutArray_%d)" % (j, j),
            "        .m_axis_%d_tvalid(validArray_%d)" % (j, j),
            "        .m_axis_%d_tready(nReadyArray_%d)" % (j, j),
        ]
    return (
        "// DynaRapid adapter, generated by finn.util.dynarapid\n"
        "// NOTE: rst is FINN's active-low ap_rst_n\n"
        "module %s (\n%s\n);\n    %s_wrapper inst (\n%s\n    );\nendmodule\n"
        % (dcp, ",\n".join(ports), bd_name, ",\n".join(conns))
    )


def synth_tcl(model, node, dcp, comp_dir, synth_dir, part, clk_ns, threads):
    """Vivado script: single-node block design + adapter, OOC synthesis, util + metadata."""
    inst = getCustomOp(node)
    ins, outs = stream_interfaces(node)
    helper = CreateStitchedIP(part, clk_ns)
    helper.create_cmds += inst.code_generation_ipi()
    helper.connect_clk_rst(node)
    helper.connect_s_axis_external(node)
    helper.connect_m_axis_external(node)
    bd_name = dcp + "bd"
    adapter = os.path.join(comp_dir, dcp + ".v")
    with open(adapter, "w") as f:
        f.write(
            adapter_verilog(
                dcp, bd_name, len(ins), len(outs), [w for _, w in ins], [w for _, w in outs]
            )
        )
    ip_dirs = "$::env(FINN_ROOT)/finn-rtllib/memstream %s" % inst.get_nodeattr("ip_path")
    rw_tcl = os.path.join(dynarapid_root(), "RapidWright", "tcl", "rapidwright.tcl")
    fclk_hz = round(1e9 / clk_ns)
    bd_file = "%s/prj.srcs/sources_1/bd/%s/%s.bd" % (comp_dir, bd_name, bd_name)
    dcp_file = os.path.join(synth_dir, dcp + "_synth.dcp")
    tcl = [
        "set_param general.maxThreads %d" % threads,
        "create_project -force prj %s -part %s" % (comp_dir, part),
        "set_msg_config -id {[BD 41-1753]} -suppress",
        "set_property ip_repo_paths [list %s] [current_project]" % ip_dirs,
        "update_ip_catalog",
        'create_bd_design "%s"' % bd_name,
    ]
    tcl += helper.create_cmds + helper.connect_cmds
    tcl += [
        "set_property CONFIG.FREQ_HZ %d [get_bd_ports /ap_clk]" % fclk_hz,
        "validate_bd_design",
        "save_bd_design",
        "add_files -norecurse [make_wrapper -files [get_files %s] -top]" % bd_file,
        "add_files -norecurse %s" % adapter,
        "set_property top %s [current_fileset]" % dcp,
        # synthesize the whole block design in one global run
        "set_property synth_checkpoint_mode None [get_files %s]" % bd_file,
        "generate_target all [get_files %s]" % bd_file,
        "synth_design -top %s -part %s -mode out_of_context" % (dcp, part),
        "write_checkpoint -force %s" % dcp_file,
        "write_edif -force %s" % dcp_file.replace(".dcp", ".edf"),
        "report_utilization -packthru -file %s" % os.path.join(synth_dir, dcp + ".util"),
        "source %s" % rw_tcl,
        "generate_metadata %s %s 0" % (dcp_file, synth_dir),
    ]
    return "\n".join(tcl) + "\n"


def build_component(
    model,
    node,
    dcp,
    work_dir,
    library_dir,
    part,
    clk_ns,
    num_shapes=1,
    vivado_threads=1,
    target_util=0.8,
    pblock_mode="fast",
    pblock_parallel=1,
):
    """Synthesize one component and generate its pre-implemented library entry.

    Returns a dict with status and per-stage seconds. Skips all work if the
    component already exists in the library.
    """
    res = {"dcp": dcp, "node": node.name, "op_type": node.op_type}
    if os.path.isfile(os.path.join(library_dir, dcp + ".bin.data")):
        res.update(status="cached", synth_s=0.0, pblock_s=0.0, database_s=0.0)
        return res
    env = dynarapid_env(work_dir, library_dir, part, clk_ns, vivado_threads)
    synth_dir = os.path.join(work_dir, "vhdlSynthDCPs")
    comp_dir = os.path.join(work_dir, "components", dcp)
    os.makedirs(comp_dir, exist_ok=True)
    os.makedirs(synth_dir, exist_ok=True)
    short = PART_TO_DYNARAPID[part]

    # 1. out-of-context synthesis of the single-node block design + adapter
    meta = os.path.join(synth_dir, dcp + "_synth_0_metadata.txt")
    rc, res["synth_s"] = 0, 0.0
    if not os.path.isfile(meta):
        tcl_file = os.path.join(comp_dir, "synth.tcl")
        with open(tcl_file, "w") as f:
            f.write(synth_tcl(model, node, dcp, comp_dir, synth_dir, part, clk_ns, vivado_threads))
        rc, res["synth_s"] = run_vivado(
            tcl_file, os.path.join(comp_dir, "synth.log"), comp_dir, env
        )
    if rc != 0 or not os.path.isfile(meta):
        res["status"] = "synth_failed"
        return res
    synth_log = os.path.join(comp_dir, "synth.log")
    if (
        os.path.isfile(synth_log)
        and "could not open $readmem" in open(synth_log, errors="ignore").read()
    ):
        # a memory initialization file was not found: the netlist would have empty memories
        os.remove(meta)
        res["status"] = "synth_missing_meminit"
        return res

    # 2. pblock placement and routing with exposed pins (DynaRapid + Vivado)
    # "shaped": DynaRapid's pin-exposing flow (three Vivado runs) with a compact pblock
    # "fast"  : a single Vivado run, port nets left for RWRoute at stitching time
    if pblock_mode == "fast":
        entry = "ch.agsl.dynarapid.pblockgenerator.GenerateFastPblocks"
        pargs = ["-part", short, "-m", dcp, "-util", str(target_util)]
        pargs += ["-parallel", str(pblock_parallel)]
    else:
        entry = "ch.agsl.dynarapid.pblockgenerator.GenerateShapedPblocks"
        pargs = ["-part", short, "-m", dcp, "-num", str(num_shapes), "-util", str(target_util)]
    rc, res["pblock_s"] = run_java(
        entry,
        pargs,
        env,
        os.path.join(comp_dir, "pblocks.log"),
    )
    comp_lib = os.path.join(library_dir, dcp)
    if (
        rc != 0
        or not os.path.isdir(comp_lib)
        or not any(f.endswith("_placedRouted.dcp") for f in os.listdir(comp_lib))
    ):
        res["status"] = "pblock_failed"
        return res

    # 3. placement database (valid relocation sites) + binary database
    rc, res["database_s"] = run_java(
        "ch.agsl.dynarapid.entry.GenerateDatabase",
        ["-part", short, "-m", dcp],
        env,
        os.path.join(comp_dir, "database.log"),
    )
    ok = rc == 0 and os.path.isfile(os.path.join(library_dir, dcp + ".bin.data"))
    res["status"] = "built" if ok else "database_failed"
    with open(os.path.join(comp_dir, "result.json"), "w") as f:
        json.dump(res, f, indent=2)
    return res
