# Copyright (C) 2026, Advanced Micro Devices, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""RTL of StreamingLaneSplit / StreamingLaneMerge (finn.custom_op.fpgadataflow.streaminglanes):
generated Verilog, one module per node, one register stage on the output side so that every
valid comes from a register (independent of any ready), full rate."""

import os

from finn.custom_op.fpgadataflow.rtlbackend import RTLBackend
from finn.custom_op.fpgadataflow.streaminglanes import StreamingLaneMerge, StreamingLaneSplit


def _pad8(w):
    return (w + 7) // 8 * 8


class _LanesRTL(RTLBackend):
    def get_nodeattr_types(self):
        my_attrs = {}
        my_attrs.update(RTLBackend.get_nodeattr_types(self))
        return my_attrs

    def _verilog(self, top):
        raise NotImplementedError

    def generate_hdl(self, model, fpgapart, clk):
        top = self.get_verilog_top_module_name()
        self.set_nodeattr("gen_top_module", top)
        d = self.get_nodeattr("code_gen_dir_ipgen")
        with open(os.path.join(d, top + ".v"), "w") as f:
            f.write(self._verilog(top))
        self.set_nodeattr("ipgen_path", d)
        self.set_nodeattr("ip_path", d)

    def get_rtl_file_list(self, abspath=False):
        f = self.get_nodeattr("gen_top_module") + ".v"
        return [os.path.join(self.get_nodeattr("code_gen_dir_ipgen"), f)] if abspath else [f]

    def code_generation_ipi(self):
        target = "./ip/verilog/rtl_ops/%s" % self.onnx_node.name
        cmd = ["file mkdir %s" % target]
        for f in self.get_rtl_file_list(abspath=True):
            cmd.append("add_files -copy_to %s -norecurse %s" % (target, f))
        cmd.append(
            "create_bd_cell -type module -reference %s %s" % (self.get_nodeattr("gen_top_module"), self.onnx_node.name)
        )
        return cmd

    def execute_node(self, context, graph):
        mode = self.get_nodeattr("exec_mode")
        if mode == "rtlsim":
            RTLBackend.execute_node(self, context, graph)
        else:
            self._python(context, graph)


class StreamingLaneSplit_rtl(StreamingLaneSplit, _LanesRTL):
    def __init__(self, onnx_node, **kwargs):
        super().__init__(onnx_node, **kwargs)

    def get_nodeattr_types(self):
        my_attrs = {}
        my_attrs.update(StreamingLaneSplit.get_nodeattr_types(self))
        my_attrs.update(_LanesRTL.get_nodeattr_types(self))
        return my_attrs

    def _python(self, context, graph):
        StreamingLaneSplit.execute_node(self, context, graph)

    def execute_node(self, context, graph):
        _LanesRTL.execute_node(self, context, graph)

    def _verilog(self, top):
        k = self.get_nodeattr("NumParts")
        w_in, w_out = self.get_instream_width(), self.get_outstream_width()
        pi, po = _pad8(w_in), _pad8(w_out)
        ports = ["    input ap_clk", "    input ap_rst_n",
                 "    input [%d:0] in0_V_TDATA" % (pi - 1), "    input in0_V_TVALID", "    output in0_V_TREADY"]
        body = ["    // output slots: a slot takes the next word when it is empty or drained this cycle"]
        free = []
        for i in range(k):
            ports += ["    output [%d:0] out%d_V_TDATA" % (po - 1, i), "    output out%d_V_TVALID" % i,
                      "    input out%d_V_TREADY" % i]
            body += ["    reg [%d:0] d%d = 0;" % (w_out - 1, i), "    reg v%d = 1'b0;" % i,
                     "    assign out%d_V_TDATA = {%s d%d};" % (i, "%d'b0," % (po - w_out) if po > w_out else "", i),
                     "    assign out%d_V_TVALID = v%d;" % (i, i)]
            free.append("(!v%d || out%d_V_TREADY)" % (i, i))
        body += ["    wire take = %s;" % " && ".join(free), "    assign in0_V_TREADY = take;",
                 "    always @(posedge ap_clk) begin", "        if (!ap_rst_n) begin"]
        body += ["            v%d <= 1'b0;" % i for i in range(k)]
        body += ["        end else if (in0_V_TVALID && take) begin"]
        for i in range(k):
            body += ["            d%d <= in0_V_TDATA[%d:%d];" % (i, (i + 1) * w_out - 1, i * w_out), "            v%d <= 1'b1;" % i]
        body += ["        end else begin"]
        body += ["            if (out%d_V_TREADY) v%d <= 1'b0;" % (i, i) for i in range(k)]
        body += ["        end", "    end"]
        return "// generated by finn StreamingLaneSplit_rtl\nmodule %s (\n%s\n);\n%s\nendmodule\n" % (
            top, ",\n".join(ports), "\n".join(body))


class StreamingLaneMerge_rtl(StreamingLaneMerge, _LanesRTL):
    def __init__(self, onnx_node, **kwargs):
        super().__init__(onnx_node, **kwargs)

    def get_nodeattr_types(self):
        my_attrs = {}
        my_attrs.update(StreamingLaneMerge.get_nodeattr_types(self))
        my_attrs.update(_LanesRTL.get_nodeattr_types(self))
        return my_attrs

    def _python(self, context, graph):
        StreamingLaneMerge.execute_node(self, context, graph)

    def execute_node(self, context, graph):
        _LanesRTL.execute_node(self, context, graph)

    def _verilog(self, top):
        k = self.get_nodeattr("NumParts")
        w_in, w_out = self.get_instream_width(), self.get_outstream_width()
        pi, po = _pad8(w_in), _pad8(w_out)
        ports = ["    input ap_clk", "    input ap_rst_n"]
        allv = []
        for i in range(k):
            ports += ["    input [%d:0] in%d_V_TDATA" % (pi - 1, i), "    input in%d_V_TVALID" % i,
                      "    output in%d_V_TREADY" % i]
            allv.append("in%d_V_TVALID" % i)
        ports += ["    output [%d:0] out0_V_TDATA" % (po - 1), "    output out0_V_TVALID", "    input out0_V_TREADY"]
        cat = ", ".join("in%d_V_TDATA[%d:0]" % (i, w_in - 1) for i in reversed(range(k)))
        body = ["    reg [%d:0] d = 0;" % (w_out - 1), "    reg v = 1'b0;",
                "    assign out0_V_TDATA = {%s d};" % ("%d'b0," % (po - w_out) if po > w_out else ""),
                "    assign out0_V_TVALID = v;",
                "    // all inputs at once, when the output register is empty or drained this cycle",
                "    wire all_valid = %s;" % " && ".join(allv),
                "    wire take = all_valid && (!v || out0_V_TREADY);"]
        body += ["    assign in%d_V_TREADY = take;" % i for i in range(k)]
        body += ["    always @(posedge ap_clk) begin", "        if (!ap_rst_n) v <= 1'b0;",
                 "        else if (take) begin d <= {%s}; v <= 1'b1; end" % cat,
                 "        else if (out0_V_TREADY) v <= 1'b0;", "    end"]
        return "// generated by finn StreamingLaneMerge_rtl\nmodule %s (\n%s\n);\n%s\nendmodule\n" % (
            top, ",\n".join(ports), "\n".join(body))
