#!/usr/bin/env python3
"""Regenerate the FIFO-sizing *cost* table (.tex) from measured wall-clock times.

Companion to ``tools/make_fifo_eval_table.py``: that one says how good the depth
vectors are, this one says what they cost to produce. Reads the JSON that
finn-plus' ``ci/experiments/timing_table.py`` writes and emits the LaTeX table in
the same layout -- one row per model, the four sizing variants as column groups.

    python3 tools/make_fifo_timing_table.py \\
        --timing $FINN_PLUS_ROOT/ci/experiments/timing.json \\
        --out chained_tav_fifo_timing_results.tex

Three costs are separated because they are paid at different times:

``TAV``   deriving the token access vectors. Measured for the tree-model
          variants, where it is a few seconds. **Not** measured for the rtlsim
          variants: that is per-node HLS synthesis plus XSI simulation, hours per
          model, done once and cached -- the figures in ``RTLSIM_HOURS`` below
          are the recorded one-off costs and are printed as a footnote rather
          than as a column, because they are not comparable to a per-build cost.
``Prep``  the four characterisation transforms the sizer depends on
          (LocalStretch, HandleBranches, Delay, ProducerDelay). Shared by every
          variant, so it is reported once per model.
``Size``  ``DeriveFIFOSizes`` itself. This is the pass under study.

``chained_tav`` derives every depth twice, with and without the causal write
bound (docs/fifo-sizing-chained-tav.md 3.7), so its single-pass time is also
recorded and the doubling is visible in the footnote.
"""

import argparse
import json

ROWS = [
    ("KWS", "kws"),
    ("CyberSec", "cybsec"),
    ("TFC-1bit", "tfc-w1a1"),
    ("TFC-2bit", "tfc-w2a2"),
    ("CNV-1bit", "cnv-w1a1"),
    ("CNV-2bit", "cnv-w2a2"),
    ("VGG10", "vgg10"),
    ("MobileNetV1", "mobilenetv1"),
    ("ResNet-50", "resnet50"),
    ("RadioML T.", "radioml"),
    ("Vision T.", "vision"),
    ("Language T.", "language"),
]

COLS = [
    ("heuristic_rtlsim", "Heuristic", "rtlsim"),
    ("heuristic_tree", "Heuristic", "tree-model"),
    ("new_rtlsim", "New Heur.", "rtlsim"),
    ("new_tree", "New Heur.", "tree-model"),
]

#: one-off, cached cost of deriving rtlsim token access vectors, in hours, as
#: recorded when each cache was built (docs/fifo-sizing-workbench.md 1)
RTLSIM_HOURS = {"resnet50": 4.0}


def secs(x):
    if x is None:
        return r"\textit{n/a}"
    if x < 0.01:
        return "<0.01"
    if x < 10:
        return "%.2f" % x
    if x < 100:
        return "%.1f" % x
    return "%.0f" % x


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--timing", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    T = json.load(open(a.timing))

    L = []
    L.append("% generated by tools/make_fifo_timing_table.py from")
    L.append("% finn-plus ci/experiments/timing_table.py -- regenerate, do not hand-edit")
    L.append(r"\begin{table}[ht]")
    L.append(r"\centering")
    L.append(
        r"\caption{Wall-clock cost of FIFO sizing, in seconds, on one core of the "
        r"build host. \textit{Prep} is the four characterisation transforms the "
        r"sizer depends on and is shared by every method; \textit{Size} is the "
        r"sizing pass itself; \textit{TAV} is the cost of deriving the token "
        r"access vectors, which for the tree-model columns is paid on every build "
        r"and for the rtlsim columns is a cached one-off (hours; see text) and is "
        r"therefore not comparable. \textit{n/a} marks the branching graphs the "
        r"per-edge heuristic cannot size at all.}"
    )
    L.append(r"\label{tab:sizing_cost}")
    L.append(r"\small")
    L.append(r"\setlength{\tabcolsep}{3pt}")
    L.append(r"\begin{tabular}{l|r|r@{\hspace{3pt}}r|r@{\hspace{3pt}}r|r@{\hspace{3pt}}r|r@{\hspace{3pt}}r}")
    L.append(r"\hline")
    L.append(
        r"Method & & \multicolumn{2}{c|}{Heuristic} & \multicolumn{2}{c|}{Heuristic}"
        r" & \multicolumn{2}{c|}{\textbf{New Heur.}} & \multicolumn{2}{c}{\textbf{New Heur.}} \\"
    )
    L.append(
        r"Mode & & \multicolumn{2}{c|}{rtlsim} & \multicolumn{2}{c|}{tree-model}"
        r" & \multicolumn{2}{c|}{rtlsim} & \multicolumn{2}{c}{tree-model} \\"
    )
    head = (
        r"Model & \rotatebox{90}{Prep {\scriptsize [s]}}"
        + r" & \rotatebox{90}{TAV {\scriptsize [s]}} & \rotatebox{90}{Size {\scriptsize [s]}}" * 4
        + r" \\"
    )
    L.append(head)
    L.append(r"\hline")

    for label, key in ROWS:
        row = T.get(key)
        if not row:
            continue
        prep = next((v.get("prep") for v in row.values() if "prep" in v), None)
        cells = [label, secs(prep)]
        for ckey, _, _ in COLS:
            c = row.get(ckey, {})
            if "error" in c or not c:
                cells += [r"\textit{n/a}", r"\textit{n/a}"]
            else:
                cells += [secs(c.get("tav")), secs(c.get("size"))]
        L.append(" & ".join(cells) + r" \\")

    L.append(r"\hline")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")

    open(a.out, "w").write("\n".join(L) + "\n")
    print("wrote %s (%d rows)" % (a.out, sum(1 for _, k in ROWS if k in T)))

    # the numbers that do not fit in the table, for the accompanying text
    print("\nfor the text:")
    for label, key in ROWS:
        row = T.get(key, {})
        n = row.get("new_rtlsim", {})
        if "size" in n and n.get("size_single_pass"):
            print("  %-12s chained_tav %6.2f s two-pass, %6.2f s single-pass (%.1fx)"
                  % (label, n["size"], n["size_single_pass"],
                     n["size"] / max(n["size_single_pass"], 1e-9)))
    for key, hours in RTLSIM_HOURS.items():
        print("  %-12s cached rtlsim TAV derivation: ~%.1f h (one-off)" % (key, hours))


if __name__ == "__main__":
    main()
